name: Deploy Cloud Functions

on:
  push:
    branches:
      - main
    paths:
      - "gcpfunctions/**"
  workflow_dispatch:

jobs:
  deploy_optimized:
    name: Deploy Optimized Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: bsc-thesis-implementation

      - name: Deploy Optimized Function
        run: |
          gcloud functions deploy optimizedFunction \
            --runtime=go121 \
            --trigger-http \
            --allow-unauthenticated \
            --source=./gcpfunctions/ \
            --entry-point=OptimizedFunction \
            --no-gen2 \
            --region=europe-west3

  deploy_baseline:
    name: Deploy Baseline Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: bsc-thesis-implementation

      - name: Deploy Baseline Function
        run: |
          gcloud functions deploy baselineFunction \
            --runtime=go121 \
            --trigger-http \
            --allow-unauthenticated \
            --source=./gcpfunctions/ \
            --entry-point=BaselineFunction \
            --no-gen2 \
            --region=europe-west3

  deploy_benchmark:
    name: Deploy Execute-Benchmark Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: bsc-thesis-implementation

      - name: Deploy Execute-Benchmark Function
        run: |
          gcloud functions deploy executeBenchmark \
            --runtime=go121 \
            --trigger-http \
            --allow-unauthenticated \
            --source=./gcpfunctions/ \
            --entry-point=ExecuteBenchmark \
            --no-gen2 \
            --region=europe-west3
